[versions]
agp = "8.13.2"
fragmentKtx = "1.6.2"
gson = "2.13.2"
kotlin = "2.3.0"
lifecycleViewmodelKtx = "2.8.7"
material = "1.13.0"
swiperefreshlayout = "1.2.0"

[libraries]
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

